---
title: "Italian Polls"
author: "Matti Harrison"
date: "10/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(dplyr)
```


```{r}
polling <- read.csv("polls_IT-parliament_2018-10-01.csv") 

x <- polling %>% 
  select(date, firm, n, LN, M5S) %>% 
  gather(key= "party", value= "poll", LN, M5S)
  
x %>% 
  ggplot(aes(x=date, y=poll, color=party)) + geom_point()
```
Purpose of this document is to show polling results in Italy.

##Plotting LN 
```{r}
x %>% 
  ggplot(aes(x=date,y=LN, color = "red")) + geom_point() + 
  geom_point(aes(x=date, y=M5S, color = "blue"))
```

```{r}
x %>% 
  ggplot(aes(x=date,y=poll, color = party)) + geom_point() + 
  geom_point(aes(x=date, y=M5S, color = "blue"))
```

##Plotting 4 Parties
```{r}
y <- polling %>% 
  select(date, firm, n, LN, M5S, FIPDLFI, PD) %>% 
  gather(key= "party", value= "poll", LN, M5S, FIPDLFI, PD) %>% 
  ggplot(aes(x=date, y=poll, color=party)) + geom_smooth() + 
  geom_point(alpha=.1, size =.5) 
```


